Buddy
microsoft/snmalloc pull request #468
Opened 2022-03-02 20:30 UTC by mjp41

Missing the following features

- [ ] Lazy Decommit. The features of he `ChunkAllocator` to use time to gradually deallocate memory are not currently implemented.  The `ChunkAllocator` code needs turning into a new backend `Range`.
- [ ] Custom OE support.  This needs a slightly different backend configuration
- [ ] Blocking merging of blocks from Pal.  Some platforms should not merge blocks from the Pal. For instance, you cannot commit contiguous VirtualAllocs with a single call, so we need to prevent the buddy allocator merging them.  This is also important for CHERI support.
- [ ]  CHERI support.  The capabilities for Chunks need to be stored and passed around on CHERI.  That is currently not done.

Pushing this draft PR, to get some early feedback, and also to get some CI feedback.

2022-03-03 02:46 UTC, SchrodingerZhu commented
Not closely related to this PR. But I wonder whether we should do sth like [jemalloc](https://github.com/jemalloc/jemalloc/blob/eabe88916290fec452048eaa1abe1cd52a794339/include/jemalloc/internal/jemalloc_preamble.h.in#L57) for linux PAL to improve its compatibility.

2022-03-03 12:58 UTC, SchrodingerZhu commented
> @SchrodingerZhu, what Linux environments support the flag in the kernel but don't provide it in the headers?

Centos 7.9, for example?

2022-03-10 16:38 UTC, nwf requested changes
Some issues identified by the CHERI compiler.  Beyond the suggestions here, we're tickling a deprecation warning (`CHERI_PERM_CHERIABI_VMMAP` has been renamed to `CHERI_PERM_SW_VMEM`; I'll raise a separate PR) and there appears to be a missing set-bounds in a large alloc path.  Will debug the latter and get back to you, but wanted to flag these for your review.

2022-03-10 16:38 UTC, nwf commented on src/backend/largebuddyrange.h
> +      *ptr = r | (*ptr & (MIN_CHUNK_SIZE - 1)) | BACKEND_MARKER;
The CHERI compiler is again a little upset about this expression: `*ptr` is a capability, `*ptr & ...` is a capability, and `r` is a capability, so `r | (*ptr & ...)` again triggers its uncertainty of provenance.
```suggestion
      *ptr = r | statc_cast<address_t>(*ptr & (MIN_CHUNK_SIZE - 1)) | BACKEND_MARKER;
```

2022-03-10 16:38 UTC, nwf commented on src/backend/largebuddyrange.h
> +      MetaEntry& entry = Pagemap::template get_metaentry_mut<false>(larger);
```suggestion
      MetaEntry& entry = Pagemap::template get_metaentry_mut<false>(static_cast<address_t>(larger));
```

2022-03-10 16:38 UTC, nwf commented on src/backend/smallbuddyrange.h
> +          reinterpret_cast<FreeChunk*>(address_cast(*ptr) & MASK));
The CHERI compiler correctly flags this as the construction of a pointer from a provenance-free integer.
```suggestion
          reinterpret_cast<FreeChunk*>((*ptr).unsafe_uintptr() & MASK));
```

2022-03-10 16:38 UTC, nwf commented on src/mem/metaslab.h
> +    static constexpr uintptr_t BOUNDARY_BIT = 1;
```suggestion
    static constexpr address_t BOUNDARY_BIT = 1;
```

2022-03-10 16:38 UTC, nwf commented on src/mem/metaslab.h
> +      meta = (other.meta & ~BOUNDARY_BIT) | (meta & BOUNDARY_BIT);
Another ambiguous provenance case.

```suggestion
      meta = (other.meta & ~BOUNDARY_BIT) | static_cast<address_t>(meta & BOUNDARY_BIT);
```

2022-03-10 17:04 UTC, mjp41 commented
I am going to leave migrating the slow decommit behaviour to a future PR as this doesn't seem to be an issue with perf currently.

And adding new Range types should be much nicer now.

2022-03-11 15:15 UTC, rmn30 commented on src/backend/palrange.h
> +        static PalRange range{};
I guess this is some C++ism? Maybe worth a comment to at least name the pattern being used?

2022-03-11 16:46 UTC, nwf approved these changes
If CI's happy, I think I'm happy.  Thanks for folding in the CHERI bounds.

2022-03-11 18:16 UTC, merged